code-squad/swift-coordinate

CoordinateCalculator/.gitignore
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculatorTest/CoordinateCalculatorTest.swift
CoordinateCalculator/CoordinateCalculatorTest/Info.plist
CoordinateCalculator/CoordinateCalculatorTest/MyLineTest.swift
CoordinateCalculator/CoordinateCalculatorTest/MyRectTest.swift
CoordinateCalculator/CoordinateCalculatorTest/MyTriangleTest.swift
CoordinateCalculator/Package.swift
CoordinateCalculator/README.md
CoordinateCalculator/Sources/CoordinateCalculator/ANSICode.swift
CoordinateCalculator/Sources/CoordinateCalculator/OutputView.swift
CoordinateCalculator/Sources/CoordinateCalculator/main.swift

1. 점, 선, 삼각형, 사각형 구조체를 만들고, 관련 계산기 함수를 구현했습니다.
2. 각각의 구조체의 함수를 테스트 하기위해 유닛 테스트를 생성했습니다.
- 유닛테스트는 다음 단계에서 더 큰 입력 데이터로 테스트 할 생각입니다.
3. ANSI Code를 터미널에 표현하기 위한 스위프트 패키지를 생성했습니다.

Coordinate step1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/Sources/CoordinateCalculator/InputView.swift
CoordinateCalculator/Sources/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/Sources/CoordinateCalculator/OutputView.swift
CoordinateCalculator/Sources/CoordinateCalculator/main.swift

ANSICode를 출력하기 위해 swift package를 사용하였습니다.
swift package를 통해 실행되는 파일은 CoordinateCalculator/Sources에 있습니다.
최대한 커밋 단위를 미션의 요구사항 단위로 하려고 노력했습니다.

Coordinate step2

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculatorTests/CoordinateCalculatorTests.swift
CoordinateCalculator/CoordinateCalculatorTests/Info.plist
Sources/swift-coordinate/InputView.swift
Sources/swift-coordinate/MyPoint.swift
Sources/swift-coordinate/OutputView.swift
Sources/swift-coordinate/main.swift

[Update]좌표가 입력된 위치에 특수문자 출력

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/CustomErrors.swift
CoordinateCalculator/CoordinateCalculator/Figure.swift
CoordinateCalculator/CoordinateCalculator/FigureCreator.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculatorTests/CoordinateCalculatorTests.swift
CoordinateCalculator/CoordinateCalculatorTests/FigureCreatorTest.swift
Sources/swift-coordinate/CustomErrors.swift
Sources/swift-coordinate/Figure.swift
Sources/swift-coordinate/FigureCreator.swift
Sources/swift-coordinate/InputView.swift
Sources/swift-coordinate/MyLine.swift
Sources/swift-coordinate/MyPoint.swift
Sources/swift-coordinate/MyTriangle.swift
Sources/swift-coordinate/OutputView.swift
Sources/swift-coordinate/main.swift

Jake Coordinate step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/CustomErrors.swift
CoordinateCalculator/CoordinateCalculator/FigureCreator.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/PointInvalidationChecker.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculatorTests/CoordinateCalculatorTests.swift
CoordinateCalculator/CoordinateCalculatorTests/FigureCreatorTest.swift
CoordinateCalculator/CoordinateCalculatorTests/PointInvalidCheckerTest.swift
Sources/swift-coordinate/CustomErrors.swift
Sources/swift-coordinate/FigureCreator.swift
Sources/swift-coordinate/InputView.swift
Sources/swift-coordinate/MyLine.swift
Sources/swift-coordinate/MyRect.swift
Sources/swift-coordinate/MyTriangle.swift
Sources/swift-coordinate/OutputView.swift
Sources/swift-coordinate/PointInvalidationChecker.swift
Sources/swift-coordinate/main.swift

InputView의 역할을 축소시키는 방향으로 리팩토링 하면서 4개의 점 입력시 사각형의 점과 넓이를 출력하는 부분 구현했습니다.

Jake Coordinate step5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Controller/CoordinateTrixCalculator.swift
CoordinateCalculator/CoordinateCalculator/Model/CoordinateModel.swift
CoordinateCalculator/CoordinateCalculator/Model/MyLine.swift
CoordinateCalculator/CoordinateCalculator/Model/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/Utility/Generatrix.swift
CoordinateCalculator/CoordinateCalculator/View/OutputView.swift
CoordinateCalculator/CoorinateCalculatorUnitTest/CoorinateCalculatorUnitTest.swift

#Napster Coordinate step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Figure/Figure.swift
CoordinateCalculator/CoordinateCalculator/Figure/MyLine.swift
CoordinateCalculator/CoordinateCalculator/Figure/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/Figure/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestCoordinateCalculator.swift

1. MyTriangle 구조체 추가
2. MyTriangle 넓이 관련 테스트 케이스 추가
3. OutputView Error 열거형 추가

[AMING] 좌표계산기 4단계 확인 부탁드립니다

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyShapeCreator.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/UnitTestCoordinateCalculator/Info.plist
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestCoordinateCalculator.swift

Elly Coordinate step5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

Make axis of coordinates

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MakingShape.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyShape.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/SyntaxChecker.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoorinateCalculatorUnitTest/CoorinateCalculatorUnitTest.swift

1. 삼각형 부분 추가
2. MyLine 및 MyTriangle 내부에 같은 좌표 체크하는 에러체크 메소드 추가
3. MyShape에서 각 케이스별로 2번 메소드를 호출하여 에러 체크 후 Shape객체생성
4. main에 3번 에러관련 내용 추가

[hoon] Coordinate step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyShape.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

1. 삼각형 구조체를 추가하였습니다.
2. 삼각형 넓이를 출력하기 위한 함수를 구현했습니다.

[Jack] Coordinate step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyShape.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift

1. 사각형 구조체를 추가하였습니다.
2. 직사각형인 사각형만 출력하기 위해 OutputView구조체를 개선하였습니다.

[Jack] Coordinate step5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

coordinate calculator step1 PR  보냅니다

CoordinateCalculator step1, add outputview

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

Add inputView, add draw coordinates point

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/GrammarChecker.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[hyun] Coordinate step3

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[hyun] Coordinate step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/GrammarChecker.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyCalculate.swift
CoordinateCalculator/CoordinateCalculator/MyFactory.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyShape.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[hyun] Coordinate step5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/UnitTestCoordinates/Info.plist
CoordinateCalculator/UnitTestCoordinates/UnitTestCoordinates.swift

[hyun] make unit test

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

struct OutputView 추가, clean()와  drawAxis()함수 추가

[rhino] 좌표계산기 step1 진행했습니다

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/ShapeCreator.swift
CoordinateCalculator/UnitTestCC/Info.plist
CoordinateCalculator/UnitTestCC/UnitTestCC.swift

[rhino] 좌표계산기 마무리 진행했습니다.

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[Mason] Coordinate step1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/UnitTestCoordinateCalculator/Info.plist
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestCoordinateCalculator.swift
CoordinateCalculator/View/OutputView.swift

Coordinate step1(시작하기)

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/FigureFactory.swift
CoordinateCalculator/CoordinateCalculator/InputChecker.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Protocols.swift
CoordinateCalculator/CoordinateCalculator/main.swift

* InputChecker가 좌표를 2개에서 3개로 받도록 범위가 확장되었습니다.
* 기존 코드에서 MyTriangle 객체를 추가하였습니다.
*  좌표의 축을 그리는 메서드는 의존하는 데이터가 없기에 static으로 변경하였습니다.

Coordinate step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/FigureFactory.swift
CoordinateCalculator/CoordinateCalculator/InputChecker.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/main.swift

* 사각형 입력을 위해 InputChecker의 입력허용 범위를 4로 변경
* 사각형 입력을 위해 FigureFactory에서 사각형생성 case 추가
* MyRect 구조체 구현
* 원점과 크기의 값을 넘겨주어 MyRect 생성하기 위해 FigureFactory에 함수추가(makeOriginAndSize), MyRect의 이니셜라이저 추가(MyPoint, CGSize)
* FigureFactory의 MyRect를 생성하기 전 origin과 size를 만들면서 직사각형이 아닌경우 오류처리(재입력 요구)

[Mason] Coordinate step5

---

.gitattributes
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Checker.swift
CoordinateCalculator/CoordinateCalculator/Cutter.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Pointer.swift
CoordinateCalculator/CoordinateCalculator/Regex.swift
CoordinateCalculator/CoordinateCalculator/RegexFormMaker.swift
CoordinateCalculator/CoordinateCalculator/main.swift

coordinate step2 fix [PR]

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Checker.swift
CoordinateCalculator/CoordinateCalculator/Extracter.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/PointerMaker.swift
CoordinateCalculator/CoordinateCalculator/Regex.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculatorTest/CoordinateCalculatorTest.swift
CoordinateCalculator/CoordinateCalculatorTest/Info.plist

Drake] Coordinate step5 PR

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/main.swift

test commit입니다(화면클리어 및 좌표그리기 메쏘드 추가).

1st test commit

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/main.swift

Reverts code-squad/swift-coordinate#95

Revert "1st test commit"

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/main.swift

test commit입니다(화면클리어 및 좌표그리기 메쏘드 추가).
- 다시 보내드립니다

1st test commit - again

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/ANSICode.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/SyntaxChecker.swift
CoordinateCalculator/CoordinateCalculator/main.swift

coordinate-step2

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

- 파일 단위로 OutputView 구조체 생성
- 프로퍼터 없이 단순 출력을 위해 클래스 메소드로 구현

OutputView

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Protocols.swift
CoordinateCalculator/CoordinateCalculator/main.swift

3단계를 구현하였습니다.
- 모든 검증 과정을 ( 숫자 범위 ) InputView.Validation에서 수행하도록 수정하였습니다.

Coordinate step3

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/FigureGenerator.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift

사각형 입력 및 출력을 구현하였습니다. 
- 기존에 구현해놓은 Over1DFigureProtocol로 OutputView에선 어떠한 추가코드를 작성해주지 않아도 됬습니다.
- InputView에서는 오로지 점들의 parsing만 진행해주었고 사각형의 검증은 FigureGenerator에서 진행해주는 것이 옳다고 판단하였습니다.

Coordinate step5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/UnitTestCoordinateCalculator/Info.plist
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestCoordinateCalculator.swift

테스트 코드 작성 
1. 테스트코드 비교를 위해 Equatable 사용
2. 리턴값이 Protocol 인 경우에는 각 모양객체로 다운캐스팅 한 후에 비교

Coordinate step6

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/ErrorMessage.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/ProtocolFactory.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculator/protocol.swift
CoordinateCalculator/CoordinateCalculatorUnitTest/CoordinateCalculatorUnitTest.swift
CoordinateCalculator/CoordinateCalculatorUnitTest/Info.plist
CoordinateCalculator/CoordinateCalculatorUnitTest/MyLineTest.swift

좌표계산기 4단계 삼각형 입력과 출력 진행, 어색했던 makeCoordinates 함수 이름 변경

coordinate-step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/ErrorMessage.swift
CoordinateCalculator/CoordinateCalculator/InputValueCheck.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/ProtocolFactory.swift
CoordinateCalculator/CoordinateCalculator/main.swift

coordinate-step5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

OutputView의 drawAxis() 함수를 구현하여 좌표축을 그렸습니다.

좌표계산기 - 시작하기 (좌표축 그리기)

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

- 좌표를 그려주는 drawAxis()와 OutputView 구조체를 구현했습니다.
- iTerm에서 실행되도록 하였습니다.

좌표계산기 1단계 - 시작하기

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Shape.swift
CoordinateCalculator/CoordinateCalculator/ShapeGenerator.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestShape.swift

- 삼각형을 입출력할 수 있도록 `MyTriangle` 구조체를 추가했습니다.
- `ShapeGenerator.generateShape()` 메소드에 `MyTriangle` 을 리턴하는 경우를 추가했습니다. 
- 추가된 내용에 대한 단위테스트를 수정했습니다.

좌표계산기 4단계 - 삼각형 입력과 출력

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator.xcodeproj/xcshareddata/xcschemes/CoordinateCalculator-itermView.xcscheme
CoordinateCalculator/CoordinateCalculator.xcodeproj/xcshareddata/xcschemes/CoordinateCalculator.xcscheme
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculator/outputView.swift

- OutputView 구조체를 추가
- drawAxis() 함수를 구현
- main에서 OutputView 구조체 drawAxis() 함수를 호출
- 콘솔 화면상에 결과를 확인하기 위해서 터미널에서 실행

Jumpingbilly step1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

- [InputView] 구조체 생성
- [MyPoint] 구조체 생성
- [InputView] readInput() 추가
- [InputView] getXYPoint() 생성
- [InputView] validCheck() 생성
- [InputView] 재입력시 문구 추가
- [OutputView] showPoint() 추가

Coordinate step02

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

- OutputView 구조체 생성 -> drawAxis() , clearBackground() 메소드 구현

Justin step1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/xcshareddata/xcschemes/CoordinateCalculator-terminal.xcscheme
CoordinateCalculator/CoordinateCalculator/CheckUserInput.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/ShapeCreator.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculator/possibleCharacterSet.swift

- 사용자의 입력을 받아오는 구조체 InputView() 구현
- 사용자 입력 받는 readInput() 메소드 구현
- 입력 값이 범위 안의 값인지 검사하는 IsOverFlowNumber() 메소드 구현
- 화면에 출력하는 구조체 OutputView() 구현
- 화면에 MyPoint의 위치에 점을 찍는 drawPoint() 메소드 구현
- Point의 정보를 가지고 있는 구조체 MyPoint() 구현

Justin-Step2

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/PrintView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

PrintView
- eraseDisplay : 화면 초기화
- drawCoordinate : 좌표 그리기

Bran - CoordinateCalculator Step1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Check.swift
CoordinateCalculator/CoordinateCalculator/FigureCreator.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/ValidCheck.swift
CoordinateCalculator/CoordinateCalculator/main.swift

- MyLine 객체 생성
- FigureCreator 객체 생성
- 선도 입력을 받을 수 있게 하고 선을 입력했을때는 두 점 사이의 거리도 같이 출력하도록 했습니다.

Coordinate step03

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/createFigure.swift
CoordinateCalculator/CoordinateCalculator/errorCheck.swift
CoordinateCalculator/CoordinateCalculator/figure.swift
CoordinateCalculator/CoordinateCalculator/figureCreator.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculator/myLine.swift
CoordinateCalculator/CoordinateCalculator/myPoint.swift
CoordinateCalculator/CoordinateCalculator/myTriangle.swift
CoordinateCalculator/CoordinateCalculator/outputView.swift

- Step1,2,3 구현 내용 유지
- 3개의 점을 입력받을 때 에러핸들링 ```ErrorCheck```
- 삼각형 구조체 ```MyTriangle``` & 넓이를 구하는 메소드 구현
- 세개의 좌표를 입력받을 때, 도형을 만들어주는 구조체 ```CreateFigure``` 구현
- 삼각형의 좌표가 찍히고, 넓이가 출력되도록 ```OutputView``` 구조체 구현

Billy - 좌표계산기 step4

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/FigureCreator.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/UnitTestCoordinateCalculator/Info.plist
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestCheck.swift
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestFigure.swift
CoordinateCalculator/UnitTestCoordinateCalculator/UnitTestFigureCreator.swift

- 삼각형도 입력 받도록 하였습니다.
- 삼각형을 입력하면 넓이도 출력되도록 하였습니다.
- 테스트 코드를 작성하였습니다.

Coordinate step04

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/CheckUserInput.swift
CoordinateCalculator/CoordinateCalculator/InputState.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/ShapeCreator.swift
CoordinateCalculator/CoordinateCalculator/ShapeDistinguish.swift

- `CheckUserInput`객체에 직사각형 성립조건 검사 추가 및 좌표가 5개 이상들어올 경우 에러 리턴
- 사각형 넓이 CGSize 이용하여 계산
- 사각형 생성 시 origin 원점과 CGsize 사이즈만 넘겨 LeftTop, RightBottom 좌표 계산하는 로직 구현

Justin step5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Check.swift
CoordinateCalculator/CoordinateCalculator/FigureCreator.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/main.swift

- 사각형도 입력 가능하도록 하였습니다.
- 사각형 출력시 넓이도 출력 되도록 하였습니다.
- 좌표는 최대 4개까지만 입력 가능하도록 하였습니다.
- 직사각형만 입력이 가능하도록 하였습니다.

Coordinate step05

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/errorCheck.swift
CoordinateCalculator/CoordinateCalculator/extension.swift
CoordinateCalculator/CoordinateCalculator/figureCreator.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/CoordinateCalculator/myRect.swift
CoordinateCalculator/CoordinateCalculator/outputView.swift
CoordinateCalculator/unitTestCoordinateCalculator/Info.plist
CoordinateCalculator/unitTestCoordinateCalculator/unitTestErrorCheck.swift
CoordinateCalculator/unitTestCoordinateCalculator/unitTestFigureCreator.swift
CoordinateCalculator/unitTestCoordinateCalculator/unitTestMyLine.swift
CoordinateCalculator/unitTestCoordinateCalculator/unitTestMyPoint.swift
CoordinateCalculator/unitTestCoordinateCalculator/unitTestMyRect.swift
CoordinateCalculator/unitTestCoordinateCalculator/unitTestMyTriangle.swift

- extension 적용, 코드 수정
- MyRect 구조체 생성 및 사각형 출력 구현
- ErrorCheck에 직사각형을 입력하는 경우와 그렇지 않은 경우 처리 구현

Billy - 좌표계산기 5단계 

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/Mypoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

Coordinate step2 - 좌표 입력과 출력 을 진행했습니다.

Coordinate step2 - 좌표 입력과 출력

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyShape.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift

[swift-coordinate-step4] 삼각형 추가 : 삼각형 구조체 정의, 초기화로직, 출력문 , 계산

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyShape.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/RectValidator.swift
CoordinateCalculator/CoordinateCalculator/TextValidator.swift

MyRect 추가 했습니다. step5 PR 보냅니다.

[swift-coordinate : step5 ] MyRect 추가

---

coordinateCalculator/coordinateCalculator.xcodeproj/project.pbxproj
coordinateCalculator/coordinateCalculator/FigureCreate.swift
coordinateCalculator/coordinateCalculator/InputView.swift
coordinateCalculator/coordinateCalculator/MyLine.swift
coordinateCalculator/coordinateCalculator/MyTriangle.swift

[NORI] 좌표계산기 step4 완료

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[SK] 좌표 계산기 5-1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

Step5-1_Aiden

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

- OutputView 구조체 생성하였습니다.
- drawAxis() 함수를 구현하였습니다.

[MINDY] 좌표 Step-1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/ErrorMessage.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

step5-2 aiden

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/ANSICode.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/README.md

- OutputView 구현
- static method drawAxis() : clear 후 좌표 출력
- type method 를 main.swift에서 호출

[흰] step 5-1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator.xcodeproj/xcshareddata/xcschemes/CoordinateCalculator on Terminal.xcscheme
CoordinateCalculator/CoordinateCalculator.xcodeproj/xcshareddata/xcschemes/CoordinateCalculator.xcscheme
CoordinateCalculator/CoordinateCalculator/ANSICode.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

* OutputView 구조체 추가
* main에서 OutputView 구조체 drawAxis() 함수를 호출 하도록 변경
* console (iterm 2)에서 정상 출력 확인

[Doran] STEP 5-1 

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Validator.swift
CoordinateCalculator/CoordinateCalculator/main.swift
README.md

- main에서 값을 입력받고, 값이 유효하지 않으면 에러메세지를 출력하고 재입력을 받습니다
- MyPoint 인스턴스를 생성하고, OutputView에 생성한 mypoint 인스턴스를 전달해, 해당하는 좌표의 점을 출력합니다.

[MINDY] 좌표계산기 Step-2

---

ANSICode.md
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Distinct.swift
CoordinateCalculator/CoordinateCalculator/ErrorMessage.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

Step5-3 aiden

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/ANSICode.swift
CoordinateCalculator/CoordinateCalculator/InputRefinary.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
README.md

- 입력을 "(x,y)" 형태로 받도록 하였습니다.
- (입력/좌표 스플릿/숫자변환/범위체크)에 대한 예외처리
- 좌표점 출력은  redBright 가 나오도록 설정했습니다.

[Doran] STEP 5-2

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/CoordinateCalculator.swift
CoordinateCalculator/CoordinateCalculator/Line.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Point.swift
CoordinateCalculator/CoordinateCalculator/Rectangle.swift
CoordinateCalculator/CoordinateCalculator/Triangle.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[SK] 좌표 계산기 5-5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/Distinct.swift
CoordinateCalculator/CoordinateCalculator/Figure.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Shame.swift
CoordinateCalculator/CoordinateCalculator/main.swift
DTO와VO.md
Substring과 Subsequence.md

Step5-4_aiden

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

1. OutputView 구조체 추가
2. drawAxis()함수 구현

step 5-1 (Ogi)

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/xcshareddata/xcschemes/CoordinateCalculator.xcscheme
CoordinateCalculator/CoordinateCalculator/Convertor.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/Inspection.swift
CoordinateCalculator/CoordinateCalculator/Inspector.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift
CoordinateCalculator/README.md

- 각 역할에 맞도록 구조체를 생성하였습니다.
- InputView: 입력 담당
- OutputView: 출력 담당
- MyPoint: 좌표
- Inspection: 입력값 검증
- Convertor: 값 변환
- 전체적인 구조는 입력값을 받으면 Inspeciton 구조체를 통해 검증하고 MyPoint 구조체로 객체를 넘겨서 OutputView를 통해 화면에 출력하도록 구성하였습니다.
- README를 작성하였습니다.

[제잉] Coordinate step2

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Distinct.swift
CoordinateCalculator/CoordinateCalculator/ErrorMessage.swift
CoordinateCalculator/CoordinateCalculator/Figure.swift
CoordinateCalculator/CoordinateCalculator/Guide.swift
CoordinateCalculator/CoordinateCalculator/MyCrossPoint.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/VerifyRect.swift
CoordinateCalculator/CoordinateCalculator/main.swift

기존에 요구했던 사항은 각좌표와 평행한 사각형이 출력되도록 요구하였지만, 어떠한 각도든지 직사각형이 되면 출력하도록 로직을 구현해보았습니다. 이에 따라 MyRect구조체 내부 로직이 기존의 요구사항과 조금 다릅니다.

Step5-5 aiden

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/AxisDrawable.swift
CoordinateCalculator/CoordinateCalculator/FigureFactory.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

1. MyTriangle struct 추가
- AxisDrawable, ValueComputable 채택
- initializer 2개 구현 - with pair/ with point instance
2. protocol AxisDrawable 
- getPoints() => points property 로 수정
(각 도형의 point는 연산의 결과가 아닌 상태라고 판단. 외부에서 보기에 property로 접근하는게 적절함.)
3. FigureFactory : MyTriangle 객체 생성 기능 추가
- 입력, 파싱, 변환한 결과 pair가 3개일 경우 삼각형 객체 생성

[흰] Step 4

---

CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[BLU] Coordinate Step1

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/AxisDrawable.swift
CoordinateCalculator/CoordinateCalculator/CoordinateError.swift
CoordinateCalculator/CoordinateCalculator/CoordinateValidator.swift
CoordinateCalculator/CoordinateCalculator/FigureFactory.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/README.md

1. MyPoint - Hashable protocol 준수
- 목적 : MyTriangle 에서 points 구현, MyRect가 직/정사각형인지 체크
2. MyRect 추가
- 두가지 initializer 구현
- size property로 넓이 계산
3. FigureFactory
- MyRect 생성 추가
- 각 도형 생성 과정 method로 분리

[흰] Step 5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

5-1 프로그램설계하기

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Calculable.swift
CoordinateCalculator/CoordinateCalculator/Converter.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Validator.swift

- MyRect 구조체 추가
- 직사각형 검사
- Calculable 프로토콜 추가
- 계산결과에 대한 설명, 계산결과
- 문구와 값을 분리해서 전달해 OutputView에서 조합

[MINDY] 좌표계산기 Step-5

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Process.swift
CoordinateCalculator/CoordinateCalculator/main.swift

Coodinate step2

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/Calculable.swift
CoordinateCalculator/CoordinateCalculator/Converter.swift
CoordinateCalculator/CoordinateCalculator/Enum.swift
CoordinateCalculator/CoordinateCalculator/Factory.swift
CoordinateCalculator/CoordinateCalculator/InputView.swift
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/MyRect.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/Validator.swift
CoordinateCalculator/CoordinateCalculator/drawable.swift
CoordinateCalculator/CoordinateCalculator/main.swift

피드백 부탁드립니다 ~ !
1. 사각형 출력 위한 Enum case 추가
2. rectangle case 추가
3. Factory 함수에 rectangle 함수 추가
4. MyRect.swift 파일 생성
5. 사각형 만들기에 대한 예외처리 추가
6. 띄어쓰기와 변수명 수정, 코드의 위치 수정

Coordinate step5(Ogi)

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/CoordinateChecker+Validator.swift
CoordinateCalculator/CoordinateCalculator/Extensions/String+Matches.swift
CoordinateCalculator/CoordinateCalculator/Message.swift
CoordinateCalculator/CoordinateCalculator/NumberParser.swift
CoordinateCalculator/CoordinateCalculator/Protocols/Measurable.swift
CoordinateCalculator/CoordinateCalculator/ShapeConverter.swift
CoordinateCalculator/CoordinateCalculator/Shapes/MyLine.swift
CoordinateCalculator/CoordinateCalculator/Shapes/MyPoint.swift
CoordinateCalculator/CoordinateCalculator/Shapes/MyRect.swift
CoordinateCalculator/CoordinateCalculator/Shapes/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/Views/InputView.swift
CoordinateCalculator/CoordinateCalculator/Views/OutputView.swift
CoordinateCalculator/CoordinateCalculator/main.swift

[BLU] Coordinate step5 new

---

CoordinateCalculator/CoordinateCalculator.xcodeproj/project.pbxproj
CoordinateCalculator/CoordinateCalculator/MyLine.swift
CoordinateCalculator/CoordinateCalculator/MyTriangle.swift
CoordinateCalculator/CoordinateCalculator/OutputView.swift
CoordinateCalculator/CoordinateCalculator/ShapeMaker.swift

Coodinate step4
